### ISSUE TITLE
Switch to type-schema once it's ready

### ISSUE THREAD

**Issue by tamj0rd2** [tamj0rd2/ncdc#36]
https://github.com/vega/ts-json-schema-generator/issues/101#issuecomment-565855600

**Comment by domoritz** [comment]
Maybe you can take ts-json-schema-generator for a spin first since it's been hardened for a few years already.

**Comment by tamj0rd2** [comment]
Closing this as it seems like this is going to take a long time. Switched to ts-json-schema-generator for now.

**Comment by domoritz** [comment]
I'll be maintaining ts-json-schema-generator until something else is fully feature-complete as we rely on the generator for Vega-Lite.
