### ISSUE TITLE
Serve mode | noEmit not working with incremental

### ISSUE THREAD

**Issue by oshdev** [tamj0rd2/ncdc#378]
## Summary

When a TypeScript error occurs, I'd like to see what the error was in the output. Currently I get

> error: An error occurred while validating one of your configured fixtures:
> Could not compile your typescript source files

and no details on the error.

At the same time, when I run the tsc I get no errors, so I imagine I have something not set up correctly for NCDC and not sure how to debug it.

**Comment by tamj0rd2** [comment]
Can you use the `-v` flag and send the output?

Also, your ncdc and typescript version?

**Comment by oshdev** [comment]
yarn tsc -v
Version 3.9.7

yarn ncdc --version
0.13.0

yarn fake -v
$ ncdc serve ./src/deals-service/cdc/deals-service.yml 4000 --watch -v
verbose: Error 5053: Option 'noEmit' cannot be specified with option 'incremental'.
error: An error occurred while validating one of your configured fixtures:
Could not compile your typescript source files

> Error 5053: Option 'noEmit' cannot be specified with option 'incremental'.

This pretty much answers the question

**Comment by tamj0rd2** [comment]
I think I introduced a bug in the latest version. You shouldn't have to set noEmit to false. I'll have a look later

**Comment by tamj0rd2** [comment]
I think a temporary workaround is to not use --watch, or to downgrade to 0.12.0

**Comment by tamj0rd2** [comment]
This is fixed in newer versions of ncdc.
